version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: gamify-mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: gamify_db
      MYSQL_USER: gamify_user
      MYSQL_PASSWORD: gamify_pass

    ports:
       - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: